Repository RedisBloom/redisbloom-go, pull requests merged in 2021-06, with the labels that each got.

#37 Add support for T-Digest sketch to the client
  client.go
  client_test.go
Labels: enhancement

#38 Added make fmt and make lint rules
  .circleci/config.yml
  Makefile
  go.mod
  go.sum
Labels: x:quality

#39 Examples to T-Digest functions
  example_client_test.go
Labels: documentation
